{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 1. What is the role of try and exception block?\n",
    "\n",
    "Ans. The try block lets us test a block of code for errors. Whereas, The except block lets us handle the error.\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 2. What is the syntax for a basic try-except block?\n",
    "\n",
    "Ans. \n",
    "\n",
    "try:\n",
    "    # some code that may raise an exception\n",
    "except ExceptionType:\n",
    "    # code to handle the exception"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 3. What happens if an exception occurs inside a try block and there is no matching except block?\n",
    "\n",
    "Ans. If an exception occurs inside a try block and there is no matching except block, the program will terminate with an unhandled exception error. \n",
    "The rest of the code in the try block will be skipped, and any finally block will be executed before the program stops. "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 4. What is the difference between using a bare except block and specifying a specific exception type?\n",
    "\n",
    "Ans. Using a bare except block (except:) and specifying a specific exception type (except SomeException:) serve different purposes in handling exceptions.\n",
    "\n",
    "As bare except block catches any type of exception occurs within the corresponding 'try' block. It is a general catch-all, and will handle all exceptions regardless of their type.\n",
    "Ex :\n",
    "        try:\n",
    "            # some code that may raise an exception\n",
    "        except:\n",
    "            # handle any exception\n",
    "        \n",
    "As in specifying a specific exception type (except SomeException: ), catches only the specified type of exception (e.g., except ValueError:). \n",
    "It allows us to handle different exceptions differently, providing more control over the exception-handling process.\n",
    "Ex : \n",
    "        try:\n",
    "            # some code that may raise a ValueError\n",
    "        except ValueError:\n",
    "            # handle only ValueError\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 5. Can you have nested try-except blocks in Python? If yes, then give an example.\n",
    "\n",
    "Ans. \n",
    "\n",
    "try:\n",
    "    # Outer try block\n",
    "    num = input(\"Enter a number: \")\n",
    "\n",
    "    try:\n",
    "        # Inner try block\n",
    "        num1 = int(num)\n",
    "        result = 10 / num1\n",
    "        print(\"Result:\", result)\n",
    "\n",
    "    except ZeroDivisionError:\n",
    "        print(\"Cannot divide by zero in the inner try block.\")\n",
    "\n",
    "except ValueError:\n",
    "    print(\"Invalid input. Please enter a valid number.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 6. Can we use multiple exception blocks, if yes then give an example.\n",
    "\n",
    "Ans. \n",
    "\n",
    "try:\n",
    "    num1 = int(input(\"Enter your num1: \"))\n",
    "    num2 = int(input(\"Enter your num2: \"))\n",
    "    res = num1/num2\n",
    "    print(\"Result:\",res)\n",
    "\n",
    "except ValueError:\n",
    "    print(\"Invalid input. Enter only numbers\")\n",
    "except ZeroDivisionError:\n",
    "    print(\"Cannot divide by Zero\")\n",
    "except Exception as e:\n",
    "    print(\"An error occured,\"e)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 7. Write the reason due to which following errors are raised:\n",
    "\n",
    "(a) EOFError : EOFError is a type of error which is raised when an operation that expects the end of a file is performed, \n",
    "but the end of the file is not encountered as expected.\n",
    "\n",
    "(b) FloatingPointError : FloatingPointError is a type of error is  raised in Python when a floating-point operation fails to produce a valid result. \n",
    "This typically occurs in situations where the result of a floating-point calculation is undefined or not representable due to limitations in the floating-point representation.\n",
    "\n",
    "(c) IndexError : IndexError is a type of error is raised when you try to access an index in a sequence (such as a list, tuple, or string) that is outside the valid range of indices.\n",
    "\n",
    "(d) MemoryError : MemoryError is a type of error is raised when an operation or expression attempts to allocate more memory than the system can provide. \n",
    "This typically occurs when your program exceeds the available memory resources, and the Python interpreter cannot fulfill a request for additional memory.\n",
    "\n",
    "(e) OverflowError : OverflowError is a type of error is raised when the result of an arithmetic operation exceeds the representational limits of the data type involved. \n",
    "This typically occurs with integer operations that go beyond the maximum or minimum values that can be stored.\n",
    "\n",
    "(f) TabError : TabError is a type of error is raised when there is an issue related to the use of tabs and spaces for indentation. Python relies on consistent indentation \n",
    "to define the structure of the code, and mixing tabs and spaces in an inconsistent manner can lead to this error.\n",
    "\n",
    "(g) ValueError : ValueError is a type of error is raised when an operation or function receives an argument of the correct type but with an invalid or inappropriate value. \n",
    "This exception is often used to indicate that a function cannot work with the provided input value because it is outside the expected range or doesn't meet certain criteria."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 8. Write code for the following given scenario and add try-exception block to it.\n",
    "\n",
    "(a) Program to divide two numbers\n",
    "\n",
    "try:\n",
    "    num1 = int(input(\"Enter your num1: \"))\n",
    "    num2 = int(input(\"Enter your num2: \"))\n",
    "    res = num1/num2\n",
    "    if num2 == 1:\n",
    "        raise Exception(\"don't give 1\")\n",
    "except ZeroDivisionError:\n",
    "    print(\"Number cannot be divided by Zero.\")\n",
    "except ValueError:\n",
    "    print(\"Invalid input. Enter only numbers.\")\n",
    "except Exception as e:\n",
    "    print(\"An exception occured\\n\",e)\n",
    "else:\n",
    "    print(\"Result:\", res)\n",
    "\n",
    "(b) Program to convert a string to an integer\n",
    "\n",
    "a = input(\"Enter your string: \")\n",
    "\n",
    "try:\n",
    "    res = int(a)\n",
    "    print(\"Conversion successful! Result:\",res)\n",
    "except ValueError:\n",
    "    print(\"Conversion failed. Please enter valid integer string\")\n",
    "\n",
    "(c) Program to access an element in a list\n",
    "    \n",
    "l1 = [1,2,3,4,5]\n",
    "\n",
    "try:\n",
    "    index = int(input(\"Enter the index to access in the list: \"))\n",
    "    value = l1[index]\n",
    "    print(f\"Value at index {index}: {value}\")\n",
    "except IndexError:\n",
    "    print(\"Invalid index. Please enter a valid index within the range of the list.\")\n",
    "except ValueError:\n",
    "    print(\"Invalid input. Please enter a valid integer for the index\")\n",
    "\n",
    "(d) Program to handle a specific exception\n",
    "\n",
    "try :\n",
    "    nume = int(input(\"Enter the numerator: \"))\n",
    "    deno = int(input(\"Enter the denominator: \"))\n",
    "    res = nume/deno\n",
    "\n",
    "    if deno == 0:\n",
    "        raise ZeroDivisionError(\"Cannot divide by zero.\")\n",
    "    if nume == 0:\n",
    "        raise Exception(\"Cannot be divided by 0\")\n",
    "   \n",
    "    print(\"Result:\",res)\n",
    "\n",
    "except ZeroDivisionError:\n",
    "    print(\"Error: Cannot divide by zero.\")\n",
    "except ValueError:\n",
    "    print(\"Error: Please enter valid integers for the numerator and denominator.\")\n",
    "except Exception as e:\n",
    "    print(f\"An unexpected error occured: {e}\")\n",
    "\n",
    "(e) Program to handle any exception\n",
    "\n",
    "try:\n",
    "    nume = int(input(\"Enter the numerator: \"))\n",
    "    deno = int(input(\"Enter the denominator: \"))\n",
    "\n",
    "    result = nume / deno\n",
    "\n",
    "    if deno == 0:\n",
    "        raise ZeroDivisionError(\"Cannot divide by zero.\")\n",
    "\n",
    "    print(\"Result:\", result)\n",
    "\n",
    "except Exception as e:\n",
    "    print(f\"An error occurred: {e}\")\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "myenv",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
